version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Seoul"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]